<?php
declare(strict_types=1);

// Pogony SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

PogonyUtility::setRegistrar(function (PogonyUtility $u): void {
    $u->clean = [PogonyClean::class, 'call'];
    $u->done = [PogonyDone::class, 'call'];
    $u->make_error = [PogonyMakeError::class, 'call'];
    $u->feature_add = [PogonyFeatureAdd::class, 'call'];
    $u->feature_hook = [PogonyFeatureHook::class, 'call'];
    $u->feature_init = [PogonyFeatureInit::class, 'call'];
    $u->fetcher = [PogonyFetcher::class, 'call'];
    $u->make_fetch_def = [PogonyMakeFetchDef::class, 'call'];
    $u->make_context = [PogonyMakeContext::class, 'call'];
    $u->make_options = [PogonyMakeOptions::class, 'call'];
    $u->make_request = [PogonyMakeRequest::class, 'call'];
    $u->make_response = [PogonyMakeResponse::class, 'call'];
    $u->make_result = [PogonyMakeResult::class, 'call'];
    $u->make_point = [PogonyMakePoint::class, 'call'];
    $u->make_spec = [PogonyMakeSpec::class, 'call'];
    $u->make_url = [PogonyMakeUrl::class, 'call'];
    $u->param = [PogonyParam::class, 'call'];
    $u->prepare_auth = [PogonyPrepareAuth::class, 'call'];
    $u->prepare_body = [PogonyPrepareBody::class, 'call'];
    $u->prepare_headers = [PogonyPrepareHeaders::class, 'call'];
    $u->prepare_method = [PogonyPrepareMethod::class, 'call'];
    $u->prepare_params = [PogonyPrepareParams::class, 'call'];
    $u->prepare_path = [PogonyPreparePath::class, 'call'];
    $u->prepare_query = [PogonyPrepareQuery::class, 'call'];
    $u->graphql_body = [PogonyGraphql::class, 'body'];
    $u->graphql_errors = [PogonyGraphql::class, 'errors'];
    $u->result_basic = [PogonyResultBasic::class, 'call'];
    $u->result_body = [PogonyResultBody::class, 'call'];
    $u->result_headers = [PogonyResultHeaders::class, 'call'];
    $u->transform_request = [PogonyTransformRequest::class, 'call'];
    $u->transform_response = [PogonyTransformResponse::class, 'call'];
});
